# - Find Po4a
# this module looks for po4a
#
# PO4A_EXECUTABLE - the full path to po4a
# PO4A_FOUND - If false, don't attempt to use po4a.

FIND_PROGRAM(PO4A_EXECUTABLE po4a)

MARK_AS_ADVANCED(
PO4A_EXECUTABLE
)

IF (NOT PO4A_EXECUTABLE)
SET(PO4A_FOUND "NO")
ELSE (NOT PO4A_EXECUTABLE)
SET(PO4A_FOUND "YES")
ENDIF (NOT PO4A_EXECUTABLE)

IF (NOT PO4A_FOUND AND Po4a_FIND_REQUIRED)
MESSAGE(FATAL_ERROR "Could not find po4a")
ENDIF (NOT PO4A_FOUND AND Po4a_FIND_REQUIRED)

