from scons_util import *

Import(['env'])
env = env.Clone()

vercmp_sources = [
	'vercmp.c',
]
vercmp = [ ]

ImportLibPacman(env)

if env['static']:
	vercmp.append(env.Program('vercmp.static', vercmp_sources))

if env['shared']:
	vercmp.append(env.Program('vercmp', vercmp_sources))

for i in vercmp:
	env.Depends(i, '#lib')
