#!/bin/sh

do_depmod()
{
	local ver
	
	if [ -x /usr/bin/readlink -a -h /boot/vmlinuz ]; then
		ver="$(/usr/bin/readlink /boot/vmlinuz 2> /dev/null)"
		if [ -n "$ver" -a -x /sbin/depmod ]; then
			/sbin/depmod --all "${ver/vmlinuz-/}"
		fi
	fi
}

op=$1
shift
$op $*
